# Generated by Django 6.0.4 on 2026-06-28 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Chat', max_length=255)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_explanations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('concept', 'Concept'), ('project', 'Project'), ('course', 'Course'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('product', 'Product'), ('learning_path', 'Learning Path')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('target_title', models.CharField(max_length=255)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.financialgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_alignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('spending', 'Spending Alert'), ('savings', 'Savings Opportunity'), ('budget', 'Budget Insight'), ('goal', 'Goal Progress'), ('educational', 'Educational Suggestion'), ('recommendation', 'Recommendation')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_pace', models.CharField(choices=[('slow', 'Slow & Thorough'), ('moderate', 'Moderate'), ('fast', 'Fast & Concise')], default='moderate', max_length=20)),
                ('learning_style', models.CharField(choices=[('visual', 'Visual'), ('reading', 'Reading/Writing'), ('interactive', 'Hands-On/Interactive'), ('video', 'Video/Watching')], default='interactive', max_length=20)),
                ('current_difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('preferred_content_types', models.JSONField(blank=True, default=list)),
                ('topics_of_interest', models.JSONField(blank=True, default=list)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('concept', 'Concept'), ('project', 'Project'), ('course', 'Course'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('product', 'Product'), ('learning_path', 'Learning Path')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('target_title', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_summary', models.JSONField(blank=True, default=dict)),
                ('spending_patterns', models.JSONField(blank=True, default=dict)),
                ('income_patterns', models.JSONField(blank=True, default=dict)),
                ('budget_health', models.JSONField(blank=True, default=dict)),
                ('savings_metrics', models.JSONField(blank=True, default=dict)),
                ('goals_summary', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_context', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
